#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:

df=pd.read_csv('/content/drive/MyDrive/data/supermarket_sales.csv')
df.head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,17:15,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [22]:
profit_max=df.groupby('Branch')['gross income'].sum()
profit_max

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

In [23]:
profit_max.idxmax()

'C'

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [20]:
revenue_max = pd.pivot_table(
    df,
    index=['Branch', 'City'],
    values='Total',
    aggfunc='sum'
)
revenue_max

                        Total
Branch City
A      Yangon     106200.3705
B      Mandalay   106197.6720
C      Naypyitaw  110568.7065

In [21]:
revenue_max.idxmax()

Total    (C, Naypyitaw)
dtype: object

Як можемо побачити, найбільший дохід та прибуток маємо у гілці С наших філій, м.Naypyitaw. Спробуємо проаналізувати далі дані, щоб дати відповідь на запитання, чим це обумовлено, і чи варто будувати ще одгу філію в місті.

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [53]:
invoices_by_category = pd.pivot_table(
    df,
    index='Branch',
    columns='Product line',
    values='Invoice ID',
    aggfunc='count'
)

invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [29]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

Спробуємо на основі датасету сформулювати три гіпотези стосовно профілю покупців та іхніх вподобань, на основі яких можна було б спрогнозувати іхню поведінку - а отже і продажі - в майбутньому. Також спробємо дати відповідь стосовно будівництва ще однієї філії в місті з найбільшим доходом ( гілка С).
1. Хто саме найбільше здіцснює покупок: тобто дослідимо самих покупців, це Member або Normal( члени клубу лояльності або сторонні покупці), а також гендерні відмінності- Жінки/Чоловіки- і чи побачимо суттєву різниицю та кореляції між цими показниками та покупками, що вони здійснили і в яких філіях ?
2. Що саме купують: які категорії товарів купують найбільше і в яких філіях, на який середній чек, а також порівняємо середні ціни на ці товари і кількість товарів в чеку.
3. Коли купують найбільше: чи є залежність між часом та періодом здійснення покупок та кількістю покупок,статтю, наявністю членства Membership?

In [4]:
#Знайдемо суму доходу по філіях і порівняємо показники колонок Member та Normal
revenue_cust_type = pd.pivot_table(
    df,
    index='Branch',
    columns=['Customer type'],
    values='Total',
    aggfunc='sum'
)

revenue_cust_type

Customer type      Member     Normal
Branch
A              53637.4755  52562.895
B              53704.6860  52492.986
C              56881.2825  53687.424

Як бачимо,в усіх філіях покупці з картками лояльності(Member) купили товарів на більші суми,ніж незареєстровані покупці - а отже,має сенс залучати якомога більше покупців до членства. В філії С також і маємо найбільший показник по продажах, зроблених учасниками карток лояльності.

In [8]:
 #Дослідимо чи є гендерні відмінності у покупців різних філій
 revenue_gender = pd.pivot_table(
    df,
    index='Branch',
    columns=['Gender'],
    values='Total',
    aggfunc='sum'
)

revenue_gender

Gender     Female        Male
Branch
A       53269.167  52931.2035
B       52928.295  53269.3770
C       61685.463  48883.2435

ЯК бачимо, суттєвих відмінностей в статі покупців філій А та В немає.
Суттєво більше доходу в філії С принесли саме жінки, тоді як чоловіки в цій філії -найменше доходу. Це може бути важливою інформацією для подальшого аналізу, тож має сенс копнути глибше в цьому напрямі - дослідити членство жінок, категорії продуктів, які наібільше купували, середні чеки та кількість товарів в них

In [89]:
# Порахуємо річний дохід покупок покупців різної статі та членства, і порівняємо результати
revenue_customers = pd.pivot_table(
    df,
    index='Branch',
    columns=['Gender', 'Customer type'],
    values='Total',
    aggfunc='sum'
)

revenue_customers

Gender             Female                    Male
Customer type      Member      Normal      Member      Normal
Branch
A              26643.0675  26626.0995  26994.4080  25936.7955
B              26850.4320  26077.8630  26854.2540  26415.1230
C              34653.4440  27032.0190  22227.8385  26655.4050

In [91]:
revenue_customers.idxmax()

Gender  Customer type
Female  Member           C
        Normal           C
Male    Member           A
        Normal           C
dtype: object

Знову бачимо по філіях А та В відсутність якогось значимого перекосу в одну зі сторін статі та членства, тоді як в С маємо чітку тенденцію значимого доходу, що принесли жінки-покупці як мембери, так і незареєстровані.

In [38]:
# Обчислимо кількість інвойсів по гендерній ознаці та членству
invoice_customers=pd.pivot_table(
    df,
    index='Branch',
    columns=['Customer type','Gender'],
    values='Invoice ID',
    aggfunc='count'
)
invoice_customers

Customer type Member      Normal
Gender        Female Male Female Male
Branch
A                 80   87     81   92
B                 85   80     77   90
C                 96   73     82   77

Філії А та Б показують теж стабільні результати по статі та членству без значних стрибків, але у філії С знову зі значимим відривом лідирують жінки-мембери, тоді як продажі серед чоловіків в цій філії просідають у порівнянні з іншими філіями

Можемо зробити висновок про загальну тененцію по філії С - жінки-покупці  принесли найбільший дохід,як мембери, так і незареєстровані, тоді як чоловіки -найменший по філіях.
1. Таким чином, як висновок по гіпотезі 1 можна зробити висновок: дохід по філіях А і В не мав особливих відмінностей залежно від статі та членства, але у філії С продажі з найвищим доходом приносять жінки з членством карток лояльності магазину. Тепер досліджуємо інші дві гіпотези - які саме товари і коли купують більше покупці, чим забезпечується більший дохід.

In [18]:
# Дослідимо, товари яких категорій  в яких філіях продавалися найбільше
products_max = pd.pivot_table(
    df,
    index='Branch',
    columns=['Product line'],
    values='Total',
    aggfunc='mean'
)

products_max

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,305.285225,320.245265,295.915526,268.037298,344.879931,328.350839
B,310.026245,264.730911,304.297770,376.993585,350.983290,322.390306
C,344.890445,331.693385,360.103864,319.525500,308.790067,350.265067

In [17]:
products_max.idxmax()

Product line
Electronic accessories    C
Fashion accessories       C
Food and beverages        C
Health and beauty         B
Home and lifestyle        B
Sports and travel         C
dtype: object

Лідирує знову майже в усіх категоріях по продажах філія С; дослідимо вартість товарів в філіях для порівняння ( чи не дорожче товари в С?),середній чек та кількість товарів в чеку

In [19]:
# Порахуємо суму середнього чеку у філіях
avg_check_by_branch = df.groupby('Branch')['Total'].mean()
avg_check_by_branch

Branch
A    312.354031
B    319.872506
C    337.099715
Name: Total, dtype: float64

In [23]:
avg_check_by_branch.idxmax()

'C'

In [20]:
# І також обчислимо середню кількість товарів в чеку по філіях
avg_quantity_by_branch = df.groupby('Branch')['Quantity'].mean()
avg_quantity_by_branch

Branch
A    5.467647
B    5.481928
C    5.582317
Name: Quantity, dtype: float64

In [22]:
avg_quantity_by_branch.idxmax()

'C'

Середній чек і кількість товарів вища в філії С - можна зробити висновок, що і купують більше товарів, іяк результат на вищі чеки знову в цій філії

In [40]:
#  Порівняємо середню вартість товарів у філіях
df.groupby('Branch')['Unit price'].mean()

Branch
A    54.780853
B    55.659277
C    56.609024
Name: Unit price, dtype: float64

ЯК бачимо, товари дорожчі в С - і це разом з більшою кількістю товарів в чеках може давати сумарно більші доходи.

Можемо заглибитися в категорії товарів, що купують покупці, проаналізувавши їх разом з висновками першої гіпотези - що і як купують найбільше жінки у філії С, чи є між цими двома висновками звязок?

In [7]:
# Подивимося, чт існує звязок кількості інвойсів по філіях з гендерною приналежністю
branch_c = df[df['Branch'] == 'C']
pd.pivot_table(
    branch_c,
    index='Product line',
    columns='Gender',
    values='Invoice ID',
    aggfunc='count'
)

Gender                  Female  Male
Product line
Electronic accessories      28    27
Fashion accessories         35    30
Food and beverages          38    28
Health and beauty           23    29
Home and lifestyle          25    20
Sports and travel           29    16

І знову бачимо підтвердження наших гіпотез - максимальна
 кількість інвойсів в філії С з найбільшим доходом в найбільш продаваних категоріях Fashion Accessories, Food and Beverages, Sports and Travel була зроблена саме жінками.

3. Обчислимо тепер, в який час були зроблені найбільші продажі, чи інсує тут залежність і чи є звязок з попередніми двома гіпотезами. Наприклад, чи є певні дні, коли жінки купували найбільше і яких саме товарів.

In [28]:
# Подивимося, в який день тижня в філіях маємо найбільше продажів
df['Date'] = pd.to_datetime(df['Date'])
df['day_of_week'] = df['Date'].dt.day_name()

In [30]:
day_of_week_revenue = pd.pivot_table(
    df,
    index='Branch',
    columns='day_of_week',
    values='Total',
    aggfunc='sum'
)

day_of_week_revenue

day_of_week,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
Branch,,,,,,,
A,14543.8650,14239.0605,16765.4130,17006.8185,15422.274,14955.2130,13267.7265
B,14417.7600,12734.7045,21284.4240,10415.3280,15778.623,18859.2390,12707.5935
C,14964.7155,10925.3130,18070.9725,17035.7460,14148.351,17667.7935,17755.8150

In [31]:
day_of_week_revenue.idxmax(axis=1)

Branch
A      Sunday
B    Saturday
C    Saturday
dtype: object

Найбільше продажів філії мають очікувано у вихдні дні- в суботу та неділю.

In [76]:
# Перевіримо звязок наявності карток лояльності покупців з покупками у певні дні тижня
day_of_week_gender=pd.pivot_table(
    df,
    index='day_of_week',
    columns=['Customer type'],
    values='Total',
    aggfunc='sum'
)
day_of_week_gender

Customer type      Member      Normal
day_of_week
Friday         22183.8435  21742.4970
Monday         18355.0710  19544.0070
Saturday       28122.9585  27997.8510
Sunday         25533.5535  18924.3390
Thursday       18393.6375  26955.6105
Tuesday        28689.4650  22792.7805
Wednesday      22944.9150  20786.2200

In [77]:
day_of_week_gender.idxmax(axis=1)

day_of_week
Friday       Member
Monday       Normal
Saturday     Member
Sunday       Member
Thursday     Normal
Tuesday      Member
Wednesday    Member
dtype: object

ЯК бачимо,покупок здійснюють більше мембери, причому в тому числі у вихідні ця тенденція зберігається

In [68]:
# Перевіримо, чи в філіяїх існує звязок між покупками в певні дні тижня та статтю
day_of_week_gender=pd.pivot_table(
    df,
    index='day_of_week',
    columns=['Gender','Branch'],
    values='Total',
    aggfunc='sum'
)
day_of_week_gender

Gender          Female                               Male              \
Branch               A           B           C          A           B
day_of_week
Friday       6975.4440   7619.6925   9552.6690  7568.4210   6798.0675
Monday       8651.4015   7437.1290   4323.4800  5587.6590   5297.5755
Saturday     8089.5360  10808.1750  10432.5165  8675.8770  10476.2490
Sunday       7841.5680   5357.3940   9901.8045  9165.2505   5057.9340
Thursday     7446.8625   6555.8220   6520.8255  7975.4115   9222.8010
Tuesday      8674.9845  11257.4805  10499.5065  6280.2285   7601.7585
Wednesday    5589.3705   3892.6020  10454.6610  7678.3560   8814.9915

Gender
Branch               C
day_of_week
Friday       5412.0465
Monday       6601.8330
Saturday     7638.4560
Sunday       7133.9415
Thursday     7627.5255
Tuesday      7168.2870
Wednesday    7301.1540

In [71]:
day_of_week_gender.idxmax(axis=1)

day_of_week
Friday       (Female, C)
Monday       (Female, A)
Saturday     (Female, B)
Sunday       (Female, C)
Thursday       (Male, B)
Tuesday      (Female, B)
Wednesday    (Female, C)
dtype: object

Цікава тенденція, що найбільше покупок здійснюють саме жінки, майже в усі дні тижня, найчастіше знову ж таки у філії С.

Висновок: як бачимо, філія C демонструє найвищі фінансові показники завдяки тому, що основний дохід її формують жінки, зокрема учасниці програми лояльності (Members). Вони купують частіше, беруть більше товарів у чеку та формують вищий середній чек. Найвищі пікові продажі припадають на вихідні дні (по усіх філіях), коли обсяг покупок і суми чеків зростають.

Отже, зростання доходу у філії C зумовлене поєднанням трьох факторів:
вищої активності жінок, ефективності membership-моделі та підвищеного попиту у вихідні. Ці показники необхідно ретельно вивчити задля можливого перенесення успіху філії С на інші гілки


Рекомендаціями для бізнесу будуть:

-активніше розвивати програму лояльності в усіх філіях

-посилювати ще більше маркетингову активність у вихідні

-орієнтувати частину пропозицій на жіночу аудиторію та дослідити успіх продажу певних категорій саме серед жінок-мемберів та по можливості перенести успіх цих продажів в інші дві філії

-чоловіча аудиторія та окремі категорії товарів демонструють нижчі показники, що свідчить про наявність потенціалу для зростання, який рекгмендується вивчити

-проаналізувати та підтримати слабші категорії ( реклама, зміна асортименту, вивчення попиту, трендів ітд)

-масштабувати успішну модель філії C на філії A та B